# 

# Numpy Üzerinden Array Oluşturma



In [1]:
import numpy as np

In [3]:
np.array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [4]:
np.array([3.4,5,6,7,8.9])

array([3.4, 5. , 6. , 7. , 8.9])



### Array işlemi optimizasyon ve performans verimliliği sağladığı için array içerisindeki verileri tek sabit tip şeklinde saklar.



In [6]:
np.array([3.4,5,6,7], dtype = "int")

array([3, 5, 6, 7])

In [7]:
np.array([3.4,5,6,7], dtype = "float")

array([3.4, 5. , 6. , 7. ])



## Sıfırdan Array Oluşturma



In [8]:

np.zeros(10, dtype = int)     # İstenilen sayıda sıfır oluşturma


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [11]:

np.ones((2,3),dtype = int)      # Satır ve sütun değeri girerek iki boyutlu matris oluşturma


array([[1, 1, 1],
       [1, 1, 1]])

In [12]:

np.ones(5,dtype = int)            # İstenilen sayıda bir oluşturma


array([1, 1, 1, 1, 1])

In [14]:

np.full((2,10),5, dtype = int)    # İstenilen sayıda istenilen sayıyı oluşturma    np.fonksiyon((Satır,Sütun) , İstenilen Sayı, dtype )


array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [15]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
np.arange(0,101,5)

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [20]:
np.linspace(0,1,10)   # Aralık arasında istenilen sayıda sayı oluşturma

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [22]:
np.linspace(2,5,100)

array([2.        , 2.03030303, 2.06060606, 2.09090909, 2.12121212,
       2.15151515, 2.18181818, 2.21212121, 2.24242424, 2.27272727,
       2.3030303 , 2.33333333, 2.36363636, 2.39393939, 2.42424242,
       2.45454545, 2.48484848, 2.51515152, 2.54545455, 2.57575758,
       2.60606061, 2.63636364, 2.66666667, 2.6969697 , 2.72727273,
       2.75757576, 2.78787879, 2.81818182, 2.84848485, 2.87878788,
       2.90909091, 2.93939394, 2.96969697, 3.        , 3.03030303,
       3.06060606, 3.09090909, 3.12121212, 3.15151515, 3.18181818,
       3.21212121, 3.24242424, 3.27272727, 3.3030303 , 3.33333333,
       3.36363636, 3.39393939, 3.42424242, 3.45454545, 3.48484848,
       3.51515152, 3.54545455, 3.57575758, 3.60606061, 3.63636364,
       3.66666667, 3.6969697 , 3.72727273, 3.75757576, 3.78787879,
       3.81818182, 3.84848485, 3.87878788, 3.90909091, 3.93939394,
       3.96969697, 4.        , 4.03030303, 4.06060606, 4.09090909,
       4.12121212, 4.15151515, 4.18181818, 4.21212121, 4.24242

In [23]:
np.random.normal(10,4, (3,4))         # np.random.normal(Ortalama, Standart Sapma, (Matris Oluşturma İçin Sütun ve Aralık))

array([[ 9.78091732,  8.44842038,  4.08554841,  6.2448913 ],
       [17.57893821,  2.54747452,  9.77723877,  3.37991475],
       [10.16506804,  6.58188594,  8.34293437, 11.23261796]])

In [29]:
np.random.normal(9,5, (5,5))

array([[ 8.05148833,  5.04066916, 17.00698891, 14.71747286,  0.08011897],
       [ 8.42504864, 20.44154687,  5.64591611,  7.12333461,  9.22176997],
       [ 6.92413718,  6.57843353,  5.98684941,  1.27324472, 11.30202732],
       [ 2.24229819,  6.6512465 ,  9.3007785 ,  4.46379407, 11.65027909],
       [10.36697538, 16.18403169,  8.55863462,  9.29008606, 11.45703601]])

In [30]:
np.random.randint(2,9)

2

In [31]:
np.random.randint(2,9,(10,10))

array([[8, 7, 8, 5, 3, 5, 6, 4, 2, 3],
       [4, 4, 2, 3, 7, 5, 3, 3, 7, 8],
       [5, 2, 3, 6, 5, 6, 7, 4, 3, 4],
       [2, 8, 3, 4, 3, 6, 4, 5, 2, 2],
       [4, 5, 3, 6, 4, 6, 4, 4, 6, 3],
       [6, 4, 4, 4, 2, 8, 4, 2, 5, 2],
       [5, 5, 3, 4, 3, 2, 3, 6, 6, 5],
       [8, 3, 4, 3, 3, 7, 2, 6, 5, 3],
       [8, 6, 4, 5, 5, 8, 2, 6, 7, 6],
       [6, 6, 7, 5, 7, 6, 8, 4, 5, 8]])



## **Array Özellikleri** 



 * ndim: Boyut Sayısı
* shape: Boyut Bilgisi
* size: Eleman Sayısı
* dtype: Array Veri Tipi


In [2]:
ramdom = np.random.randint(2,20, size = 15)

In [3]:
ramdom.ndim

1

In [4]:
ramdom.shape

(15,)

In [5]:
ramdom.size

15

In [45]:
ramdom.dtype

dtype('int32')

In [6]:

# Örnek I

sayı = np.arange(0,1075,10)
print(sayı)


[   0   10   20   30   40   50   60   70   80   90  100  110  120  130
  140  150  160  170  180  190  200  210  220  230  240  250  260  270
  280  290  300  310  320  330  340  350  360  370  380  390  400  410
  420  430  440  450  460  470  480  490  500  510  520  530  540  550
  560  570  580  590  600  610  620  630  640  650  660  670  680  690
  700  710  720  730  740  750  760  770  780  790  800  810  820  830
  840  850  860  870  880  890  900  910  920  930  940  950  960  970
  980  990 1000 1010 1020 1030 1040 1050 1060 1070]


In [7]:
sayı.ndim

1

In [8]:
sayı.shape

(108,)

In [9]:
sayı.size

108

In [10]:
sayı.dtype

dtype('int32')

In [53]:

# Örnek II

liste = np.random.randint(1,20,(5,5))
print("İki Boyutlu Array Listesi:",liste)


İki Boyutlu Array Listesi: [[11 16  4  4  5]
 [ 6  2  5  5  4]
 [12  5 15  6 12]
 [10  5 17  9  9]
 [12 17  8 15  4]]


In [55]:
liste.ndim         # Array'in matris olup olmadığını söyler

2

In [56]:
liste.shape

(5, 5)

In [57]:
liste.size

25

In [59]:
liste.dtype

dtype('int32')